nameOverride: ""
fullnameOverride: ""

image:
  container: "chefbook-frontend"
  registry: ""
  tag: ""
  pullPolicy: IfNotPresent

frontend:
  host: chefbook.io
  ingressClass: nginx
  tls:
    issuer: letsencrypt
    secretName: letsencrypt

podAnnotations: {}

service:
  type: ClusterIP
  port: 80

replicaCount: 3

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
